server:
  port: 8443
  servlet:
    context-path: /
  ssl:
   enabled: true
   key-store: src/main/resources/bootsecurity.p12
   key-store-password: bootsecurity
   key-store-type: PKCS12
   key-alias: bootsecurity
# 5.7이하는 아래의 코드를 사용할것!!!!!
# com.mysql.jdbc.Driver
# jdbc:mysql://localhost:3306/cosmysql
# 다음아래 부터는 6.0이상버전
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cos?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cos
    password: bitc5600
    
    
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
  security:
    user:
      name: cos
      password: bitc5600
 